### ISSUE TITLE
Установить систему

### ISSUE THREAD

**Issue by imcatwhocode** [b4ck5p4c3/HMI#2]
Нужно подготовить платформу к работе:
 - [x] Установить Debian
 - [x] Настроить удалённый доступ по SSH
 - [x] Настроить сетевое соединение
 - [x] Настроить автоматический вход в систему
 - [x] Настроить автоматическое открытие Chromium в kiosk mode

**Comment by imcatwhocode** [comment]
@p-hash

**Comment by p-hash** [comment]
Сделано на той железке, что валяется в спейсе.

ssh доступен с thinkpad'а: `ssh hid`

user debian запускает chrome в kiosk mode. кастомизируется тут `/home/debian/start-chromium.sh`
