### ISSUE TITLE
Подключить PN532 и проверить работу libnfc

### ISSUE THREAD

**Issue by imcatwhocode** [b4ck5p4c3/HMI#3]
Нужно проверить подключение PN532, собрать и установить libnfc.

Критерием успешного завершения задачи служит стабильная работа команды `nfc-poll`.

**Comment by imcatwhocode** [comment]
@p-hash

**Comment by p-hash** [comment]
Сделано на той железке, что валяется в спейсе. 
PN532 закреплен внутри с помощью скотча и какой-то магии. Приложенные снаружи карты читаются нормально
